version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - api-artifacts:/app/artifacts
      - chroma-data:/app/paper_db
    env_file:
      - ./.env
    depends_on:
      - db
      - chromadb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: neo4j:5-community
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data,apoc.*
    volumes:
      - neo4j-data:/data

  chromadb:
    image: chromadb/chroma
    ports:
      - "8002:8002"  
    volumes:
      - chroma-data:/chroma/.chroma

volumes:
  neo4j-data:
  chroma-data:
  api-artifacts: